self.seed = 42
Started to play
[BasePlayer] Creating regular env:  rlgpu
{'observation_space': Box(-inf, inf, (29,), float32), 'action_space': Box(-1.0, 1.0, (6,), float32), 'agents': 1, 'value_size': 1}
Building Actor
build mlp: 29
Building Critic
build mlp: 35
build mlp: 35
Building Critic Target
build mlp: 35
build mlp: 35
=> loading checkpoint '/home/vncusr/OmniIsaacGymEnvs/omniisaacgymenvs/runs/UR10Reacher/nn/last_UR10Reacher_ep_243000_rew_1979.734.pth'
[91m[1m2024-05-08 15:38:05 [32,131ms] [Error] [omni.kit.app._impl] [py stderr]: Error executing job with overrides: ['task=UR10Reacher', 'num_envs=64', 'checkpoint=omniisaacgymenvs/runs/UR10Reacher/nn/last_UR10Reacher_ep_243000_rew_1979.734.pth']
Error executing job with overrides: ['task=UR10Reacher', 'num_envs=64', 'checkpoint=omniisaacgymenvs/runs/UR10Reacher/nn/last_UR10Reacher_ep_243000_rew_1979.734.pth']
[91m[1m2024-05-08 15:38:05 [32,134ms] [Error] [omni.kit.app._impl] [py stderr]: Traceback (most recent call last):
Traceback (most recent call last):
[91m[1m2024-05-08 15:38:05 [32,134ms] [Error] [omni.kit.app._impl] [py stderr]: 
[91m[1m2024-05-08 15:38:05 [32,134ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/OmniIsaacGymEnvs/omniisaacgymenvs/scripts/rlgames_play.py", line 104, in <module>
[91m[1m    parse_hydra_configs()
  File "/home/vncusr/OmniIsaacGymEnvs/omniisaacgymenvs/scripts/rlgames_play.py", line 104, in <module>
    parse_hydra_configs()
[91m[1m2024-05-08 15:38:05 [32,134ms] [Error] [omni.kit.app._impl] [py stderr]: 
[91m[1m2024-05-08 15:38:05 [32,134ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
[91m[1m    _run_hydra(
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
[91m[1m2024-05-08 15:38:05 [32,134ms] [Error] [omni.kit.app._impl] [py stderr]: 
[91m[1m2024-05-08 15:38:05 [32,134ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
[91m[1m    _run_app(
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
[91m[1m2024-05-08 15:38:05 [32,134ms] [Error] [omni.kit.app._impl] [py stderr]: 
[91m[1m2024-05-08 15:38:05 [32,134ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
[91m[1m    run_and_report(
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
[91m[1m2024-05-08 15:38:05 [32,134ms] [Error] [omni.kit.app._impl] [py stderr]: 
[91m[1m2024-05-08 15:38:05 [32,135ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
[91m[1m    raise ex
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
[91m[1m2024-05-08 15:38:05 [32,135ms] [Error] [omni.kit.app._impl] [py stderr]: 
[91m[1m2024-05-08 15:38:05 [32,135ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
[91m[1m    return func()
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
[91m[1m2024-05-08 15:38:05 [32,135ms] [Error] [omni.kit.app._impl] [py stderr]: 
[91m[1m2024-05-08 15:38:05 [32,135ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
[91m[1m    lambda: hydra.run(
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
[91m[1m2024-05-08 15:38:05 [32,135ms] [Error] [omni.kit.app._impl] [py stderr]: 
[91m[1m2024-05-08 15:38:05 [32,135ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
[91m[1m    _ = ret.return_value
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
[91m[1m2024-05-08 15:38:05 [32,135ms] [Error] [omni.kit.app._impl] [py stderr]: 
[91m[1m2024-05-08 15:38:05 [32,135ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
[91m[1m    raise self._return_value
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
[91m[1m2024-05-08 15:38:05 [32,136ms] [Error] [omni.kit.app._impl] [py stderr]: 
[91m[1m2024-05-08 15:38:05 [32,136ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
[91m[1m    ret.return_value = task_function(task_cfg)
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
[91m[1m2024-05-08 15:38:05 [32,136ms] [Error] [omni.kit.app._impl] [py stderr]: 
[91m[1m2024-05-08 15:38:05 [32,136ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/OmniIsaacGymEnvs/omniisaacgymenvs/scripts/rlgames_play.py", line 96, in parse_hydra_configs
[91m[1m    rlg_trainer.run(module_path=module_path, experiment_dir=experiment_dir)
  File "/home/vncusr/OmniIsaacGymEnvs/omniisaacgymenvs/scripts/rlgames_play.py", line 96, in parse_hydra_configs
    rlg_trainer.run(module_path=module_path, experiment_dir=experiment_dir)
[91m[1m2024-05-08 15:38:05 [32,136ms] [Error] [omni.kit.app._impl] [py stderr]: 
[91m[1m2024-05-08 15:38:05 [32,136ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/OmniIsaacGymEnvs/omniisaacgymenvs/scripts/rlgames_train.py", line 106, in run
[91m[1m    runner.run(
  File "/home/vncusr/OmniIsaacGymEnvs/omniisaacgymenvs/scripts/rlgames_train.py", line 106, in run
    runner.run(
[91m[1m2024-05-08 15:38:05 [32,136ms] [Error] [omni.kit.app._impl] [py stderr]: 
[91m[1m2024-05-08 15:38:05 [32,136ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/rl_games/torch_runner.py", line 135, in run
[91m[1m    self.run_play(args)
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/rl_games/torch_runner.py", line 135, in run
    self.run_play(args)
[91m[1m2024-05-08 15:38:05 [32,136ms] [Error] [omni.kit.app._impl] [py stderr]: 
[91m[1m2024-05-08 15:38:05 [32,136ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/rl_games/torch_runner.py", line 121, in run_play
[91m[1m    _restore(player, args)
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/rl_games/torch_runner.py", line 121, in run_play
    _restore(player, args)
[91m[1m2024-05-08 15:38:05 [32,137ms] [Error] [omni.kit.app._impl] [py stderr]: 
[91m[1m2024-05-08 15:38:05 [32,137ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/rl_games/torch_runner.py", line 20, in _restore
[91m[1m    agent.restore(args['checkpoint'])
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/rl_games/torch_runner.py", line 20, in _restore
    agent.restore(args['checkpoint'])
[91m[1m2024-05-08 15:38:05 [32,137ms] [Error] [omni.kit.app._impl] [py stderr]: 
[91m[1m2024-05-08 15:38:05 [32,137ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/rl_games/algos_torch/players.py", line 219, in restore
[91m[1m    self.model.sac_network.actor.load_state_dict(checkpoint['actor'])
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/rl_games/algos_torch/players.py", line 219, in restore
    self.model.sac_network.actor.load_state_dict(checkpoint['actor'])
[91m[1m2024-05-08 15:38:05 [32,137ms] [Error] [omni.kit.app._impl] [py stderr]: 
[91m[1m2024-05-08 15:38:05 [32,137ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/extscache/omni.pip.torch-2_0_1-2.0.2+105.1.lx64/torch-2-0-1/torch/nn/modules/module.py", line 2041, in load_state_dict
[91m[1m    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/extscache/omni.pip.torch-2_0_1-2.0.2+105.1.lx64/torch-2-0-1/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
[91m[1m2024-05-08 15:38:05 [32,137ms] [Error] [omni.kit.app._impl] [py stderr]: 
[91m[1m2024-05-08 15:38:05 [32,137ms] [Error] [omni.kit.app._impl] [py stderr]: RuntimeError: Error(s) in loading state_dict for DiagGaussianActor:
[91m[1m	size mismatch for trunk.0.weight: copying a param with shape torch.Size([256, 29]) from checkpoint, the shape in current model is torch.Size([512, 29]).
[91m[1m	size mismatch for trunk.0.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
[91m[1m	size mismatch for trunk.2.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 512]).
[91m[1m	size mismatch for trunk.4.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([128, 256]).
[91m[1m	size mismatch for trunk.4.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
[91m[1m	size mismatch for trunk.6.weight: copying a param with shape torch.Size([12, 256]) from checkpoint, the shape in current model is torch.Size([12, 128]).
RuntimeError: Error(s) in loading state_dict for DiagGaussianActor:
	size mismatch for trunk.0.weight: copying a param with shape torch.Size([256, 29]) from checkpoint, the shape in current model is torch.Size([512, 29]).
	size mismatch for trunk.0.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for trunk.2.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 512]).
	size mismatch for trunk.4.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([128, 256]).
	size mismatch for trunk.4.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for trunk.6.weight: copying a param with shape torch.Size([12, 256]) from checkpoint, the shape in current model is torch.Size([12, 128]).
[91m[1m2024-05-08 15:38:05 [32,137ms] [Error] [omni.kit.app._impl] [py stderr]: 
[91m[1m2024-05-08 15:38:05 [32,137ms] [Error] [omni.kit.app._impl] [py stderr]: Traceback (most recent call last):
Traceback (most recent call last):
[91m[1m2024-05-08 15:38:05 [32,138ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/OmniIsaacGymEnvs/omniisaacgymenvs/scripts/rlgames_play.py", line 104, in <module>
  File "/home/vncusr/OmniIsaacGymEnvs/omniisaacgymenvs/scripts/rlgames_play.py", line 104, in <module>
[91m[1m2024-05-08 15:38:05 [32,138ms] [Error] [omni.kit.app._impl] [py stderr]:     
[91m[1m2024-05-08 15:38:05 [32,138ms] [Error] [omni.kit.app._impl] [py stderr]: parse_hydra_configs()
[91m[1m2024-05-08 15:38:05 [32,138ms] [Error] [omni.kit.app._impl] [py stderr]: 
    parse_hydra_configs()
[91m[1m2024-05-08 15:38:05 [32,138ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
[91m[1m2024-05-08 15:38:05 [32,138ms] [Error] [omni.kit.app._impl] [py stderr]:     
[91m[1m2024-05-08 15:38:05 [32,138ms] [Error] [omni.kit.app._impl] [py stderr]: _run_hydra(
[91m[1m2024-05-08 15:38:05 [32,139ms] [Error] [omni.kit.app._impl] [py stderr]: 
    _run_hydra(
[91m[1m2024-05-08 15:38:05 [32,139ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
[91m[1m2024-05-08 15:38:05 [32,139ms] [Error] [omni.kit.app._impl] [py stderr]:     
[91m[1m2024-05-08 15:38:05 [32,139ms] [Error] [omni.kit.app._impl] [py stderr]: _run_app(
[91m[1m2024-05-08 15:38:05 [32,139ms] [Error] [omni.kit.app._impl] [py stderr]: 
    _run_app(
[91m[1m2024-05-08 15:38:05 [32,139ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
[91m[1m2024-05-08 15:38:05 [32,140ms] [Error] [omni.kit.app._impl] [py stderr]:     
[91m[1m2024-05-08 15:38:05 [32,140ms] [Error] [omni.kit.app._impl] [py stderr]: run_and_report(
[91m[1m2024-05-08 15:38:05 [32,140ms] [Error] [omni.kit.app._impl] [py stderr]: 
    run_and_report(
[91m[1m2024-05-08 15:38:05 [32,140ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
[91m[1m2024-05-08 15:38:05 [32,140ms] [Error] [omni.kit.app._impl] [py stderr]:     
[91m[1m2024-05-08 15:38:05 [32,140ms] [Error] [omni.kit.app._impl] [py stderr]: raise ex
[91m[1m2024-05-08 15:38:05 [32,140ms] [Error] [omni.kit.app._impl] [py stderr]: 
    raise ex
[91m[1m2024-05-08 15:38:05 [32,140ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
[91m[1m2024-05-08 15:38:05 [32,140ms] [Error] [omni.kit.app._impl] [py stderr]:     
[91m[1m2024-05-08 15:38:05 [32,140ms] [Error] [omni.kit.app._impl] [py stderr]: return func()
[91m[1m2024-05-08 15:38:05 [32,140ms] [Error] [omni.kit.app._impl] [py stderr]: 
    return func()
[91m[1m2024-05-08 15:38:05 [32,140ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
[91m[1m2024-05-08 15:38:05 [32,141ms] [Error] [omni.kit.app._impl] [py stderr]:     
[91m[1m2024-05-08 15:38:05 [32,141ms] [Error] [omni.kit.app._impl] [py stderr]: lambda: hydra.run(
[91m[1m2024-05-08 15:38:05 [32,141ms] [Error] [omni.kit.app._impl] [py stderr]: 
    lambda: hydra.run(
[91m[1m2024-05-08 15:38:05 [32,141ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
[91m[1m2024-05-08 15:38:05 [32,141ms] [Error] [omni.kit.app._impl] [py stderr]:     
[91m[1m2024-05-08 15:38:05 [32,141ms] [Error] [omni.kit.app._impl] [py stderr]: _ = ret.return_value
[91m[1m2024-05-08 15:38:05 [32,141ms] [Error] [omni.kit.app._impl] [py stderr]: 
    _ = ret.return_value
[91m[1m2024-05-08 15:38:05 [32,141ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
[91m[1m2024-05-08 15:38:05 [32,141ms] [Error] [omni.kit.app._impl] [py stderr]:     
[91m[1m2024-05-08 15:38:05 [32,141ms] [Error] [omni.kit.app._impl] [py stderr]: raise self._return_value
[91m[1m2024-05-08 15:38:05 [32,141ms] [Error] [omni.kit.app._impl] [py stderr]: 
    raise self._return_value
[91m[1m2024-05-08 15:38:05 [32,142ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
[91m[1m2024-05-08 15:38:05 [32,142ms] [Error] [omni.kit.app._impl] [py stderr]:     
[91m[1m2024-05-08 15:38:05 [32,142ms] [Error] [omni.kit.app._impl] [py stderr]: ret.return_value = task_function(task_cfg)
[91m[1m2024-05-08 15:38:05 [32,142ms] [Error] [omni.kit.app._impl] [py stderr]: 
    ret.return_value = task_function(task_cfg)
[91m[1m2024-05-08 15:38:05 [32,142ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/OmniIsaacGymEnvs/omniisaacgymenvs/scripts/rlgames_play.py", line 96, in parse_hydra_configs
  File "/home/vncusr/OmniIsaacGymEnvs/omniisaacgymenvs/scripts/rlgames_play.py", line 96, in parse_hydra_configs
[91m[1m2024-05-08 15:38:05 [32,142ms] [Error] [omni.kit.app._impl] [py stderr]:     
[91m[1m2024-05-08 15:38:05 [32,142ms] [Error] [omni.kit.app._impl] [py stderr]: rlg_trainer.run(module_path=module_path, experiment_dir=experiment_dir)
[91m[1m2024-05-08 15:38:05 [32,142ms] [Error] [omni.kit.app._impl] [py stderr]: 
    rlg_trainer.run(module_path=module_path, experiment_dir=experiment_dir)
[91m[1m2024-05-08 15:38:05 [32,142ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/OmniIsaacGymEnvs/omniisaacgymenvs/scripts/rlgames_train.py", line 106, in run
  File "/home/vncusr/OmniIsaacGymEnvs/omniisaacgymenvs/scripts/rlgames_train.py", line 106, in run
[91m[1m2024-05-08 15:38:05 [32,142ms] [Error] [omni.kit.app._impl] [py stderr]:     
[91m[1m2024-05-08 15:38:05 [32,142ms] [Error] [omni.kit.app._impl] [py stderr]: runner.run(
[91m[1m2024-05-08 15:38:05 [32,142ms] [Error] [omni.kit.app._impl] [py stderr]: 
    runner.run(
[91m[1m2024-05-08 15:38:05 [32,143ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/rl_games/torch_runner.py", line 135, in run
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/rl_games/torch_runner.py", line 135, in run
[91m[1m2024-05-08 15:38:05 [32,143ms] [Error] [omni.kit.app._impl] [py stderr]:     
[91m[1m2024-05-08 15:38:05 [32,143ms] [Error] [omni.kit.app._impl] [py stderr]: self.run_play(args)
[91m[1m2024-05-08 15:38:05 [32,143ms] [Error] [omni.kit.app._impl] [py stderr]: 
    self.run_play(args)
[91m[1m2024-05-08 15:38:05 [32,143ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/rl_games/torch_runner.py", line 121, in run_play
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/rl_games/torch_runner.py", line 121, in run_play
[91m[1m2024-05-08 15:38:05 [32,143ms] [Error] [omni.kit.app._impl] [py stderr]:     
[91m[1m2024-05-08 15:38:05 [32,143ms] [Error] [omni.kit.app._impl] [py stderr]: _restore(player, args)
[91m[1m2024-05-08 15:38:05 [32,143ms] [Error] [omni.kit.app._impl] [py stderr]: 
    _restore(player, args)
[91m[1m2024-05-08 15:38:05 [32,143ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/rl_games/torch_runner.py", line 20, in _restore
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/rl_games/torch_runner.py", line 20, in _restore
[91m[1m2024-05-08 15:38:05 [32,143ms] [Error] [omni.kit.app._impl] [py stderr]:     
[91m[1m2024-05-08 15:38:05 [32,144ms] [Error] [omni.kit.app._impl] [py stderr]: agent.restore(args['checkpoint'])
[91m[1m2024-05-08 15:38:05 [32,144ms] [Error] [omni.kit.app._impl] [py stderr]: 
    agent.restore(args['checkpoint'])
[91m[1m2024-05-08 15:38:05 [32,144ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/rl_games/algos_torch/players.py", line 219, in restore
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/rl_games/algos_torch/players.py", line 219, in restore
[91m[1m2024-05-08 15:38:05 [32,144ms] [Error] [omni.kit.app._impl] [py stderr]:     
[91m[1m2024-05-08 15:38:05 [32,144ms] [Error] [omni.kit.app._impl] [py stderr]: self.model.sac_network.actor.load_state_dict(checkpoint['actor'])
[91m[1m2024-05-08 15:38:05 [32,144ms] [Error] [omni.kit.app._impl] [py stderr]: 
    self.model.sac_network.actor.load_state_dict(checkpoint['actor'])
[91m[1m2024-05-08 15:38:05 [32,144ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/extscache/omni.pip.torch-2_0_1-2.0.2+105.1.lx64/torch-2-0-1/torch/nn/modules/module.py", line 2041, in load_state_dict
  File "/home/vncusr/.local/share/ov/pkg/isaac_sim-2023.1.1/extscache/omni.pip.torch-2_0_1-2.0.2+105.1.lx64/torch-2-0-1/torch/nn/modules/module.py", line 2041, in load_state_dict
[91m[1m2024-05-08 15:38:05 [32,145ms] [Error] [omni.kit.app._impl] [py stderr]:     
[91m[1m2024-05-08 15:38:05 [32,145ms] [Error] [omni.kit.app._impl] [py stderr]: raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
[91m[1m2024-05-08 15:38:05 [32,145ms] [Error] [omni.kit.app._impl] [py stderr]: 
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
[91m[1m2024-05-08 15:38:05 [32,145ms] [Error] [omni.kit.app._impl] [py stderr]: RuntimeError
[91m[1m2024-05-08 15:38:05 [32,145ms] [Error] [omni.kit.app._impl] [py stderr]: : 
[91m[1m2024-05-08 15:38:05 [32,145ms] [Error] [omni.kit.app._impl] [py stderr]: Error(s) in loading state_dict for DiagGaussianActor:
[91m[1m	size mismatch for trunk.0.weight: copying a param with shape torch.Size([256, 29]) from checkpoint, the shape in current model is torch.Size([512, 29]).
[91m[1m	size mismatch for trunk.0.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
[91m[1m	size mismatch for trunk.2.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 512]).
[91m[1m	size mismatch for trunk.4.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([128, 256]).
[91m[1m	size mismatch for trunk.4.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
[91m[1m	size mismatch for trunk.6.weight: copying a param with shape torch.Size([12, 256]) from checkpoint, the shape in current model is torch.Size([12, 128]).
RuntimeError: Error(s) in loading state_dict for DiagGaussianActor:
	size mismatch for trunk.0.weight: copying a param with shape torch.Size([256, 29]) from checkpoint, the shape in current model is torch.Size([512, 29]).
	size mismatch for trunk.0.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for trunk.2.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 512]).
	size mismatch for trunk.4.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([128, 256]).
	size mismatch for trunk.4.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for trunk.6.weight: copying a param with shape torch.Size([12, 256]) from checkpoint, the shape in current model is torch.Size([12, 128]).[91m[1m2024-05-08 15:38:05 [32,146ms] [Error] [omni.kit.app._impl] [py stderr]: 